@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 06 08:35:38 -0600 2026
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Lab4_dp_tb_behav -key {Behavioral:Lab4_dp:Functional:Lab4_dp_tb} -tclbatch Lab4_dp_tb.tcl -view C:/Users/C27Jayden.Randolph/ece383_wksp/lab4/Lab04_cadet_code/Lab4_dp_tb_behav.wcfg -log simulate.log"
call xsim  Lab4_dp_tb_behav -key {Behavioral:Lab4_dp:Functional:Lab4_dp_tb} -tclbatch Lab4_dp_tb.tcl -view C:/Users/C27Jayden.Randolph/ece383_wksp/lab4/Lab04_cadet_code/Lab4_dp_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
